# Generated by Django 2.2 on 2019-04-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('channel', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=5)),
                ('os', models.CharField(max_length=255)),
                ('impressions', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('installs', models.PositiveIntegerField()),
                ('spend', models.FloatField()),
                ('revenue', models.FloatField()),
            ],
            options={
                'verbose_name': 'AdvertisingData',
                'verbose_name_plural': 'AdvertisingData',
            },
        ),
    ]
